### PR TITLE
Fix terminology in error message

### LINKED ISSUE #322: Misleading exception message when multi-instance setup is detected
### What is the problem?

Users migrating from V2 to V3 running multi-instance topology are presented with a misleading error message:

```
Pre start-up check failed: Multidatabase setup is not supported in this version of sql transport. Please see documentation for setting up non default schema per each endpoint
```

The multi-schema documentation that is referenced here will not help them resolve their problem.

### What to do about it?

The error message should be changed to reference the legacy multi-instance mode doco.

### PR DESCRIPTION
**Pull request by MarcinHoppe**
Point to upgrade guide instead of irrelevant doco

Resolves #322

### CODE REVIEW

**Comment by MarcinHoppe** [comment]
@Particular/sqlserver-transport-maintainers Please have a look at this PR.

Also, someone from @Particular/docs-maintainers might give it a glance maybe?

File: src/NServiceBus.SqlServer/Configuration/ConnectionStringsValidator.cs [hunk 1]
```diff
@@ -61,8 +61,8 @@ public bool TryValidate(List<ConnectionStringSettings> connectionSettings, out s
         const string SchemaOverridePart = "Queue Schema";
 
         const string MultiDatabaseNotSupported =
-            "Multidatabase setup is not supported in this version of sql transport. " +
-            "Please see documentation for setting up non default schema per each endpoint";
+            "Multi-instance option has been deprecated in this version of the SQL Server transport. " +
+            "Please refer to SQL Server upgrade guide for more details";
```
Comment (weralabaj) [inline src/NServiceBus.SqlServer/Configuration/ConnectionStringsValidator.cs]: > Please refer to SQL Server upgrade guide for more details

to **the** SQL Server **transport** upgrade guide ;) LGTM

**Comment by MarcinHoppe** [comment]
Thanks @weralabaj. Grammar fixed.
